version: '3.8'
services:
  mongodb:
    image: mongo:jammy
    restart: always
    ports:
      - '27017:27017'
    volumes:
      - dbdata6:/data/db
  cache:
    image: redis:alpine3.18
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    volumes:
      - cache:/data
volumes:
  dbdata6:
  cache:

